export default {
  MAKE_AS_READ_BY_ID: "MAKE_AS_READ_BY_ID",
  MAKE_ALL_AS_READ: "MAKE_ALL_AS_READ",
  START_MAKE_AS_READ: "START_MAKE_AS_READ",
  FINISH_MAKE_AS_READ: "FINISH_MAKE_AS_READ",
  LOGIN: "LOGIN",
  START_LOGIN: "START_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  CHANG_AVATAR:'CHANG_AVATAR'
};
